name: release-feature

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    if: github.ref == 'refs/heads/main' && github.repository == 'vnzzzz/agentic-development-toolkit'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Publish Dev Container Features
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"
          disable-repo-tagging: "true"
          devcontainer-cli-version: "0.88.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
