name: security

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "23 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    if: >-
      github.event_name == 'pull_request' &&
      (github.event.repository.visibility == 'public' || vars.ENABLE_GHAS_CHECKS == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0

  actions-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - name: Install zizmor
        run: python -m pip install zizmor==1.29.0
      - name: Lint GitHub Actions
        run: zizmor --min-severity high .github/workflows
